spring:
  application:
    name: letterboxd-api
  datasource:
    url: jdbc:postgresql://localhost:5432/letterboxd
    username: kennedy
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
tmdb:
  api:
    key: c8c485d9d2a00f1532fb12d7140606f2